int fork();
void xv6_exit();
void cons_putc(int c);
void puts(char* s);
int pipe(int fd[]);
int write(int fd, char* buf, int n);
int read(int fd, char* buf, int n);
void cons_puts(char* s, int size);
void exec(char* path, ...);
void puts(char* s);
int open(char* s, int n);
void close(int fd);
int mknode(char* s, short type, short major, short minor);
void printf(int fd, char* fmt, ...);
